

*   VERİ SETİ İLE İLGİLİ GENEL BAKIŞ:

In [99]:
import pandas as pd
import numpy as np

In [100]:
df= pd.read_csv('/content/persona.csv')
df.head()

   PRICE   SOURCE   SEX COUNTRY  AGE
0     39  android  male     bra   17
1     39  android  male     bra   17
2     49  android  male     bra   17
3     29  android  male     tur   17
4     49  android  male     tur   17

In [101]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5000 entries, 0 to 4999
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   PRICE    5000 non-null   int64
 1   SOURCE   5000 non-null   object
 2   SEX      5000 non-null   object
 3   COUNTRY  5000 non-null   object
 4   AGE      5000 non-null   int64
dtypes: int64(2), object(3)
memory usage: 234.4+ KB

In [102]:
df.describe()

             PRICE          AGE
count  5000.000000  5000.000000
mean     34.132000    23.581400
std      12.464897     8.995908
min       9.000000    15.000000
25%      29.000000    17.000000
50%      39.000000    21.000000
75%      39.000000    27.000000
max      59.000000    66.000000

In [103]:
df.shape

(5000, 5)

In [104]:
df.isnull().any()

PRICE      False
SOURCE     False
SEX        False
COUNTRY    False
AGE        False
dtype: bool

In [105]:
df.isnull().sum()

PRICE      0
SOURCE     0
SEX        0
COUNTRY    0
AGE        0
dtype: int64



*  Kaç unique SOURCE vardır? Frekansları nedir?

In [106]:
df['SOURCE'].nunique()

2

In [107]:
df['SOURCE'].unique()

array(['android', 'ios'], dtype=object)

In [108]:
df['SOURCE'].value_counts()

SOURCE
android    2974
ios        2026
Name: count, dtype: int64



*   Kaç unique PRICE vardır?

In [109]:
df['PRICE'].nunique()

6

In [110]:
df['PRICE'].unique()

array([39, 49, 29, 19, 59,  9])


*   Hangi PRICE'dan kaçar tane satış gerçekleşmiş?

In [111]:
df['PRICE'].value_counts()

PRICE
29    1305
39    1260
49    1031
19     992
59     212
9      200
Name: count, dtype: int64


*   Hangi ülkeden kaçar tane satış olmuş?

In [112]:
df['COUNTRY'].value_counts()

COUNTRY
usa    2065
bra    1496
deu     455
tur     451
fra     303
can     230
Name: count, dtype: int64



*   Ülkelere göre satışlardan toplam ne kadar kazanılmış?

In [113]:
df.groupby('COUNTRY').agg({'PRICE': 'sum'})

         PRICE
COUNTRY
bra      51354
can       7730
deu      15485
fra      10177
tur      15689
usa      70225



*   SOURCE türlerine göre satış sayıları nedir?

In [114]:
df['SOURCE'].value_counts()

SOURCE
android    2974
ios        2026
Name: count, dtype: int64



*   Ülkelere göre PRICE ortalamaları nedir?

In [115]:
df.groupby('COUNTRY').agg({'PRICE': 'mean'})

             PRICE
COUNTRY
bra      34.327540
can      33.608696
deu      34.032967
fra      33.587459
tur      34.787140
usa      34.007264



*   SOURCE'lara göre PRICE ortalamaları nedir?

In [116]:
df.groupby('SOURCE').agg({'PRICE': 'mean'})

             PRICE
SOURCE
android  34.174849
ios      34.069102



*   COUNTRY-SOURCE kırılımında PRICE ortalamaları nedir?

In [117]:
df.groupby(['SOURCE', 'COUNTRY']).agg({'PRICE': 'mean'})

                     PRICE
SOURCE  COUNTRY
android bra      34.387029
        can      33.330709
        deu      33.869888
        fra      34.312500
        tur      36.229437
        usa      33.760357
ios     bra      34.222222
        can      33.951456
        deu      34.268817
        fra      32.776224
        tur      33.272727
        usa      34.371703



*  COUNTRY, SOURCE, SEX, AGE kırılımında ortalama kazançlar nedir?

In [118]:
df.groupby(['COUNTRY', 'SOURCE', 'SEX', 'AGE']).agg({'PRICE': 'mean'})

                                PRICE
COUNTRY SOURCE  SEX    AGE
bra     android female 15   38.714286
                       16   35.944444
                       17   35.666667
                       18   32.255814
                       19   35.206897
...                               ...
usa     ios     male   42   30.250000
                       50   39.000000
                       53   34.000000
                       55   29.000000
                       59   46.500000

[348 rows x 1 columns]



*   Çıktıyı PRICE’a göre sıralama.

In [119]:
agg_df= df.groupby(['COUNTRY', 'SOURCE', 'SEX', 'AGE']).agg({'PRICE': 'mean'}).sort_values('PRICE', ascending=False)
agg_df.head(50)

                                PRICE
COUNTRY SOURCE  SEX    AGE
bra     android male   46   59.000000
usa     android male   36   59.000000
fra     android female 24   59.000000
usa     ios     male   32   54.000000
deu     android female 36   49.000000
                       51   49.000000
        ios     male   20   49.000000
usa     android female 47   49.000000
fra     ios     male   20   49.000000
usa     ios     male   59   46.500000
deu     android male   15   46.500000
bra     android female 30   45.666667
usa     android female 61   45.666667
tur     ios     male   24   45.000000
deu     android male   34   45.000000
tur     ios     female 18   44.000000
bra     android female 43   44.000000
        ios     female 22   44.000000
tur     android female 32   43.000000
bra     android female 39   43.000000
tur     ios     male   37   42.333333
        android male   15   42.333333
usa     ios     male   28   42.333333
bra     ios     male   43   42.333333
deu     android male   20   41.727273
usa     ios     male   30   41.727273
tur     android female 18   41.500000
usa     android male   47   41.500000
tur     android male   25   41.500000
usa     ios     female 59   41.500000
fra     android male   23   41.307692
usa     ios     male   31   41.000000
tur     android female 15   41.000000
fra     ios     male   17   40.666667
tur     ios     female 21   40.666667
        android female 31   40.666667
                male   27   40.666667
fra     android male   19   40.538462
bra     android male   24   40.428571
can     android male   30   40.250000
                       20   40.111111
usa     android male   43   39.909091
tur     android male   26   39.666667
bra     android male   40   39.625000
                       15   39.344828
usa     ios     female 19   39.285714
tur     android male   49   39.000000
bra     ios     female 19   39.000000
usa     ios     male   50   39.000000
bra     ios     female 25   39.000000



*  Indekste yer alan isimleri değişken ismine çevirme.

In [120]:
agg_df.reset_index(inplace=True)
agg_df.head(50)

   COUNTRY   SOURCE     SEX  AGE      PRICE
0      bra  android    male   46  59.000000
1      usa  android    male   36  59.000000
2      fra  android  female   24  59.000000
3      usa      ios    male   32  54.000000
4      deu  android  female   36  49.000000
5      deu  android  female   51  49.000000
6      deu      ios    male   20  49.000000
7      usa  android  female   47  49.000000
8      fra      ios    male   20  49.000000
9      usa      ios    male   59  46.500000
10     deu  android    male   15  46.500000
11     bra  android  female   30  45.666667
12     usa  android  female   61  45.666667
13     tur      ios    male   24  45.000000
14     deu  android    male   34  45.000000
15     tur      ios  female   18  44.000000
16     bra  android  female   43  44.000000
17     bra      ios  female   22  44.000000
18     tur  android  female   32  43.000000
19     bra  android  female   39  43.000000
20     tur      ios    male   37  42.333333
21     tur  android    male   15  42.333333
22     usa      ios    male   28  42.333333
23     bra      ios    male   43  42.333333
24     deu  android    male   20  41.727273
25     usa      ios    male   30  41.727273
26     tur  android  female   18  41.500000
27     usa  android    male   47  41.500000
28     tur  android    male   25  41.500000
29     usa      ios  female   59  41.500000
30     fra  android    male   23  41.307692
31     usa      ios    male   31  41.000000
32     tur  android  female   15  41.000000
33     fra      ios    male   17  40.666667
34     tur      ios  female   21  40.666667
35     tur  android  female   31  40.666667
36     tur  android    male   27  40.666667
37     fra  android    male   19  40.538462
38     bra  android    male   24  40.428571
39     can  android    male   30  40.250000
40     can  android    male   20  40.111111
41     usa  android    male   43  39.909091
42     tur  android    male   26  39.666667
43     bra  android    male   40  39.625000
44     bra  android    male   15  39.344828
45     usa      ios  female   19  39.285714
46     tur  android    male   49  39.000000
47     bra      ios  female   19  39.000000
48     usa      ios    male   50  39.000000
49     bra      ios  female   25  39.000000



*  Age değişkenini kategorik değişkene çevirip agg_df’e ekleme.

In [121]:
bins = [0, 18, 23, 30, 40, 70]
labels = ['0_18', '19_23', '24_30', '31_40', '41_70']

# Age sütununu kategorik hale getirme ve Age_Cat sütununu oluşturma
agg_df['AGE_CAT'] = pd.cut(agg_df['AGE'], bins, labels=labels)

# İlk 50 satırı gösterme
agg_df.head()

  COUNTRY   SOURCE     SEX  AGE  PRICE AGE_CAT
0     bra  android    male   46   59.0   41_70
1     usa  android    male   36   59.0   31_40
2     fra  android  female   24   59.0   24_30
3     usa      ios    male   32   54.0   31_40
4     deu  android  female   36   49.0   31_40



*   Yeni seviye tabanlı müşterileri (persona) tanımlama.

In [122]:
agg_df['customers_level_based'] = agg_df[["COUNTRY", "SOURCE", "SEX", "AGE_CAT"]].agg(lambda x: '_'.join(x).upper(), axis=1)

# İlk 50 satırı gösterme
agg_df.head(50)

   COUNTRY   SOURCE     SEX  AGE      PRICE AGE_CAT     customers_level_based
0      bra  android    male   46  59.000000   41_70    BRA_ANDROID_MALE_41_70
1      usa  android    male   36  59.000000   31_40    USA_ANDROID_MALE_31_40
2      fra  android  female   24  59.000000   24_30  FRA_ANDROID_FEMALE_24_30
3      usa      ios    male   32  54.000000   31_40        USA_IOS_MALE_31_40
4      deu  android  female   36  49.000000   31_40  DEU_ANDROID_FEMALE_31_40
5      deu  android  female   51  49.000000   41_70  DEU_ANDROID_FEMALE_41_70
6      deu      ios    male   20  49.000000   19_23        DEU_IOS_MALE_19_23
7      usa  android  female   47  49.000000   41_70  USA_ANDROID_FEMALE_41_70
8      fra      ios    male   20  49.000000   19_23        FRA_IOS_MALE_19_23
9      usa      ios    male   59  46.500000   41_70        USA_IOS_MALE_41_70
10     deu  android    male   15  46.500000    0_18     DEU_ANDROID_MALE_0_18
11     bra  android  female   30  45.666667   24_30  BRA_ANDROID_FEMALE_24_30
12     usa  android  female   61  45.666667   41_70  USA_ANDROID_FEMALE_41_70
13     tur      ios    male   24  45.000000   24_30        TUR_IOS_MALE_24_30
14     deu  android    male   34  45.000000   31_40    DEU_ANDROID_MALE_31_40
15     tur      ios  female   18  44.000000    0_18       TUR_IOS_FEMALE_0_18
16     bra  android  female   43  44.000000   41_70  BRA_ANDROID_FEMALE_41_70
17     bra      ios  female   22  44.000000   19_23      BRA_IOS_FEMALE_19_23
18     tur  android  female   32  43.000000   31_40  TUR_ANDROID_FEMALE_31_40
19     bra  android  female   39  43.000000   31_40  BRA_ANDROID_FEMALE_31_40
20     tur      ios    male   37  42.333333   31_40        TUR_IOS_MALE_31_40
21     tur  android    male   15  42.333333    0_18     TUR_ANDROID_MALE_0_18
22     usa      ios    male   28  42.333333   24_30        USA_IOS_MALE_24_30
23     bra      ios    male   43  42.333333   41_70        BRA_IOS_MALE_41_70
24     deu  android    male   20  41.727273   19_23    DEU_ANDROID_MALE_19_23
25     usa      ios    male   30  41.727273   24_30        USA_IOS_MALE_24_30
26     tur  android  female   18  41.500000    0_18   TUR_ANDROID_FEMALE_0_18
27     usa  android    male   47  41.500000   41_70    USA_ANDROID_MALE_41_70
28     tur  android    male   25  41.500000   24_30    TUR_ANDROID_MALE_24_30
29     usa      ios  female   59  41.500000   41_70      USA_IOS_FEMALE_41_70
30     fra  android    male   23  41.307692   19_23    FRA_ANDROID_MALE_19_23
31     usa      ios    male   31  41.000000   31_40        USA_IOS_MALE_31_40
32     tur  android  female   15  41.000000    0_18   TUR_ANDROID_FEMALE_0_18
33     fra      ios    male   17  40.666667    0_18         FRA_IOS_MALE_0_18
34     tur      ios  female   21  40.666667   19_23      TUR_IOS_FEMALE_19_23
35     tur  android  female   31  40.666667   31_40  TUR_ANDROID_FEMALE_31_40
36     tur  android    male   27  40.666667   24_30    TUR_ANDROID_MALE_24_30
37     fra  android    male   19  40.538462   19_23    FRA_ANDROID_MALE_19_23
38     bra  android    male   24  40.428571   24_30    BRA_ANDROID_MALE_24_30
39     can  android    male   30  40.250000   24_30    CAN_ANDROID_MALE_24_30
40     can  android    male   20  40.111111   19_23    CAN_ANDROID_MALE_19_23
41     usa  android    male   43  39.909091   41_70    USA_ANDROID_MALE_41_70
42     tur  android    male   26  39.666667   24_30    TUR_ANDROID_MALE_24_30
43     bra  android    male   40  39.625000   31_40    BRA_ANDROID_MALE_31_40
44     bra  android    male   15  39.344828    0_18     BRA_ANDROID_MALE_0_18
45     usa      ios  female   19  39.285714   19_23      USA_IOS_FEMALE_19_23
46     tur  android    male   49  39.000000   41_70    TUR_ANDROID_MALE_41_70
47     bra      ios  female   19  39.000000   19_23      BRA_IOS_FEMALE_19_23
48     usa      ios    male   50  39.000000   41_70        USA_IOS_MALE_41_70
49     bra      ios  female   25  39.000000   24_30      BRA_IOS_FEMALE_24_30



*  customers_level_based değerleri oluşturulduktan sonra bu değerlerin tekilleştirilmesi.

In [123]:
agg_df = agg_df.groupby('customers_level_based').agg({'PRICE': 'mean'})

In [127]:
agg_df.reset_index(inplace= True)
agg_df.head()

      customers_level_based      PRICE
0   BRA_ANDROID_FEMALE_0_18  35.645303
1  BRA_ANDROID_FEMALE_19_23  34.077340
2  BRA_ANDROID_FEMALE_24_30  33.863946
3  BRA_ANDROID_FEMALE_31_40  34.898326
4  BRA_ANDROID_FEMALE_41_70  36.737179

In [128]:
agg_df['customers_level_based'].value_counts()

customers_level_based
BRA_ANDROID_FEMALE_0_18    1
TUR_ANDROID_FEMALE_0_18    1
TUR_IOS_FEMALE_19_23       1
TUR_IOS_FEMALE_0_18        1
TUR_ANDROID_MALE_41_70     1
                          ..
CAN_IOS_MALE_41_70         1
CAN_IOS_MALE_31_40         1
CAN_IOS_MALE_24_30         1
CAN_IOS_MALE_0_18          1
USA_IOS_MALE_41_70         1
Name: count, Length: 109, dtype: int64


*   Yeni müşterileri (personaları) segmentlere ayırma.

In [129]:
agg_df['SEGMENT']= pd.qcut(agg_df['PRICE'], 4, labels= ['D', 'C', 'B', 'A'])
agg_df.head(20)

       customers_level_based      PRICE SEGMENT
0    BRA_ANDROID_FEMALE_0_18  35.645303       B
1   BRA_ANDROID_FEMALE_19_23  34.077340       C
2   BRA_ANDROID_FEMALE_24_30  33.863946       C
3   BRA_ANDROID_FEMALE_31_40  34.898326       B
4   BRA_ANDROID_FEMALE_41_70  36.737179       A
5      BRA_ANDROID_MALE_0_18  34.805861       B
6     BRA_ANDROID_MALE_19_23  31.673243       D
7     BRA_ANDROID_MALE_24_30  33.413919       C
8     BRA_ANDROID_MALE_31_40  34.327381       B
9     BRA_ANDROID_MALE_41_70  40.041667       A
10       BRA_IOS_FEMALE_0_18  34.900410       B
11      BRA_IOS_FEMALE_19_23  36.403846       A
12      BRA_IOS_FEMALE_24_30  34.015873       C
13      BRA_IOS_FEMALE_31_40  29.875902       D
14      BRA_IOS_FEMALE_41_70  35.340909       B
15         BRA_IOS_MALE_0_18  34.664559       B
16        BRA_IOS_MALE_19_23  34.266043       B
17        BRA_IOS_MALE_24_30  33.864865       C
18        BRA_IOS_MALE_31_40  31.566138       D
19        BRA_IOS_MALE_41_70  31.083694       D



* 33 yaşında ANDROID kullanan bir Türk kadını hangi segmente aittir ve ortalama ne kadar gelir kazandırması beklenir?

In [130]:
new_user = "TUR_ANDROID_FEMALE_31_40"
agg_df [agg_df['customers_level_based']== new_user]

       customers_level_based      PRICE SEGMENT
72  TUR_ANDROID_FEMALE_31_40  41.833333       A


*  35 yaşında IOS kullanan bir Fransız kadını hangi segmente aittir ve ortalama ne kadar gelir kazandırması beklenir?

In [131]:
new_user = "FRA_IOS_FEMALE_31_40"
agg_df [agg_df['customers_level_based']== new_user]

   customers_level_based      PRICE SEGMENT
63  FRA_IOS_FEMALE_31_40  32.818182       C